version: "3.3"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-GA-ubuntu"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    depends_on:
      - mssql
    environment:
      DB_HOST: mssql
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
