dist: xenial
language: python

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - env | grep "TEST_" > .env

script:
  # Build docker images
  - docker build --target=base -t laudio/pyodbc .
  - docker build --target=test -t laudio/pyodbc:test .

  # Spin up a mssql & pg database server containers
  - docker run --name test-mssql-server -e ACCEPT_EULA=Y -e SA_PASSWORD=${TEST_MSSQL_DB_PASSWORD} -d -p 1433:1433 microsoft/mssql-server-linux:2017-GA
  - docker run --name test-pg-server -e POSTGRES_PASSWORD=${TEST_PG_DB_PASSWORD} -d -p 5432:5432 postgres
  - sleep 10s

  # Run the test image
  - docker run --env-file=./.env --network=host laudio/pyodbc:test

after_script:
  # Stop the running containers
  - docker stop test-mssql-server
  - docker stop test-pg-server

  # List docker images that are built (Just for information.)
  - docker images laudio/*
