dist: xenial
language: python

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - env | grep "MSSQL_" > .env 

script:
  - docker build --target=base -t laudio/pyodbc .
  - docker build --target=test -t laudio/pyodbc:test .
  - docker run --env-file=./.env --network=host laudio/pyodbc:test
