version: "3.3"

services:
  mssql_source:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
      
  mssql_destination:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - mssql_source
      - mssql_destination
    environment:
      SOURCE_DB_HOST: mssql_source
      DESTINATION_DB_HOST: mssql_destination
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
